name: easy_manager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  flutter_svg: ^1.1.1+1
  http: ^0.13.4
  easy_mask: ^2.0.1  
  objectbox: ^1.6.0
  objectbox_sync_flutter_libs: ^1.6.0
  lottie: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.11
  objectbox_generator: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/svg/
    - lib/assets/animations/
  fonts:
    - family: JosefinSans
      fonts:
        - asset: lib/assets/fonts/JosefinSans/JosefinSans-Regular.ttf
        - asset: lib/assets/fonts/JosefinSans/JosefinSans-Italic.ttf
        - asset: lib/assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          